In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
site=['1G30林口中山店','1G32桃園大業店','1G33竹北文興店','1G34蘆洲集賢店','1G35板橋新埔店','1G36新營金華店','1G37永康復國店','1G38大安安和店','1G39頭份中央店','1G40三民澄清店','1G45基隆義一店','1G44嘉義興業西店','1G42永和得和店','1G46台中復興店','1G41岡山大仁店','1G43三重集美店','1G47龍潭北龍店']
import os

In [4]:
for i in site:
    os.chdir('C:/Users/RT009223/TestriteGroup\滲透率專案/01_raw data/TLW社區店/'+i)
    files=os.listdir('C:/Users/RT009223/TestriteGroup\滲透率專案/01_raw data/TLW社區店/'+i)
    start=1
    if len(files)>12:
        files=files[:12]
    for j in files:
        print(i,start,j)
        start+=1

1G30林口中山店 1 201907
1G30林口中山店 2 201908
1G30林口中山店 3 201909
1G30林口中山店 4 201910
1G30林口中山店 5 201911
1G30林口中山店 6 201912
1G30林口中山店 7 202001
1G30林口中山店 8 202002
1G30林口中山店 9 202003
1G30林口中山店 10 202004
1G30林口中山店 11 202005
1G30林口中山店 12 202006
1G32桃園大業店 1 201909
1G32桃園大業店 2 201910
1G32桃園大業店 3 201911
1G32桃園大業店 4 201912
1G32桃園大業店 5 202001
1G32桃園大業店 6 202002
1G32桃園大業店 7 202003
1G32桃園大業店 8 202004
1G32桃園大業店 9 202005
1G32桃園大業店 10 202006
1G32桃園大業店 11 202007
1G32桃園大業店 12 202008
1G33竹北文興店 1 201911
1G33竹北文興店 2 201912
1G33竹北文興店 3 202001
1G33竹北文興店 4 202002
1G33竹北文興店 5 202003
1G33竹北文興店 6 202004
1G33竹北文興店 7 202005
1G33竹北文興店 8 202006
1G33竹北文興店 9 202007
1G33竹北文興店 10 202008
1G33竹北文興店 11 202009
1G33竹北文興店 12 202010
1G34蘆洲集賢店 1 201912
1G34蘆洲集賢店 2 202001
1G34蘆洲集賢店 3 202002
1G34蘆洲集賢店 4 202003
1G34蘆洲集賢店 5 202004
1G34蘆洲集賢店 6 202005
1G34蘆洲集賢店 7 202006
1G34蘆洲集賢店 8 202007
1G34蘆洲集賢店 9 202008
1G34蘆洲集賢店 10 202009
1G34蘆洲集賢店 11 202010
1G34蘆洲集賢店 12 202011
1G35板橋新埔店 1 202003
1G35板橋新埔店 2 202004
1G35板橋新埔店 3 202005
1G35板橋新埔店 4 202006
1G35板橋新埔店 5 202007
1G35板橋新埔店 6 202008
1G35板橋新埔店 7 202009
1G35板橋新埔店 8 202010
1G35板橋新埔店 9 202011
1G35板橋新埔店 10 202012
1G35板橋新埔店 11 202101
1G36新營金華店 1 202003
1G36新營金華店 2 202004
1G36新營金華店 3 202005
1G36新營金華店 4 202006
1G36新營金華店 5 202007
1G36新營金華店 6 202008
1G36新營金華店 7 202009
1G36新營金華店 8 202010
1G36新營金華店 9 202011
1G36新營金華店 10 202012
1G36新營金華店 11 202101
1G37永康復國店 1 202004
1G37永康復國店 2 202005
1G37永康復國店 3 202006
1G37永康復國店 4 202007
1G37永康復國店 5 202008
1G37永康復國店 6 202009
1G37永康復國店 7 202010
1G37永康復國店 8 202011
1G37永康復國店 9 202012
1G37永康復國店 10 202101
1G38大安安和店 1 202005
1G38大安安和店 2 202006
1G38大安安和店 3 202007
1G38大安安和店 4 202008
1G38大安安和店 5 202009
1G38大安安和店 6 202010
1G38大安安和店 7 202011
1G38大安安和店 8 202012
1G38大安安和店 9 202101
1G39頭份中央店 1 202007
1G39頭份中央店 2 202008
1G39頭份中央店 3 202009
1G39頭份中央店 4 202010
1G39頭份中央店 5 202011
1G39頭份中央店 6 202012
1G39頭份中央店 7 202101
1G40三民澄清店 1 202009
1G40三民澄清店 2 202010
1G40三民澄清店 3 202011
1G40三民澄清店 4 202012
1G40三民澄清店 5 202101
1G45基隆義一店 1 202011
1G45基隆義一店 2 202012
1G45基隆義一店 3 202101
1G44嘉義興業西店 1 202011
1G44嘉義興業西店 2 202012
1G44嘉義興業西店 3 202101
1G42永和得和店 1 202012
1G42永和得和店 2 202101
1G46台中復興店 1 202012
1G46台中復興店 2 202101
1G41岡山大仁店 1 202012
1G41岡山大仁店 2 202101
1G43三重集美店 1 202101
1G47龍潭北龍店 1 202101

In [5]:
df01=pd.DataFrame(columns=['id','type','time','site','timeline'])
df02=pd.DataFrame(columns=['id','type','time','site','timeline'])
for i in site:
    os.chdir('C:/Users/RT009223/TestriteGroup/滲透率專案/01_raw data/TLW社區店/'+i)
    files=os.listdir('C:/Users/RT009223/TestriteGroup/滲透率專案/01_raw data/TLW社區店/'+i)
    if len(files)>12:
        files=files[:12]
    start=1
    for j in files:
        df01_2=pd.read_csv(j+'/一般卡會員活躍程度.csv',header=None,names=['id','type'])
        df01_2['time']=j
        df01_2['site']=i
        df01_2['timeline']=start
        df01_3=df01_2[-(df01_2.id.isin(df02[df02['site']==i]['id']))]
        df01=pd.concat([df01,df01_2]).reset_index(drop=True)
        df02=pd.concat([df02,df01_3]).reset_index(drop=True)
        start+=1
    print(df01.shape)
    print(df02.shape)

(23785, 5)
(15193, 5)
(43887, 5)
(26559, 5)
(69309, 5)
(43406, 5)
(96539, 5)
(61936, 5)
(126439, 5)
(80368, 5)
(148539, 5)
(94070, 5)
(162045, 5)
(102906, 5)
(178856, 5)
(113766, 5)
(190093, 5)
(122182, 5)
(198669, 5)
(128844, 5)
(206356, 5)
(135316, 5)
(212159, 5)
(140390, 5)
(217721, 5)
(145407, 5)
(223397, 5)
(150732, 5)
(227761, 5)
(154944, 5)
(231553, 5)
(158736, 5)
(233670, 5)
(160853, 5)

In [6]:
print(df01.groupby(['site'])['id'].count())
print('去重',df02.groupby(['site'])['id'].count())

site
1G30林口中山店     23785
1G32桃園大業店     20102
1G33竹北文興店     25422
1G34蘆洲集賢店     27230
1G35板橋新埔店     29900
1G36新營金華店     22100
1G37永康復國店     13506
1G38大安安和店     16811
1G39頭份中央店     11237
1G40三民澄清店      8576
1G41岡山大仁店      4364
1G42永和得和店      5562
1G43三重集美店      3792
1G44嘉義興業西店     5803
1G45基隆義一店      7687
1G46台中復興店      5676
1G47龍潭北龍店      2117
Name: id, dtype: int64
去重 site
1G30林口中山店     15193
1G32桃園大業店     11366
1G33竹北文興店     16847
1G34蘆洲集賢店     18530
1G35板橋新埔店     18432
1G36新營金華店     13702
1G37永康復國店      8836
1G38大安安和店     10860
1G39頭份中央店      8416
1G40三民澄清店      6662
1G41岡山大仁店      4212
1G42永和得和店      5017
1G43三重集美店      3792
1G44嘉義興業西店     5074
1G45基隆義一店      6472
1G46台中復興店      5325
1G47龍潭北龍店      2117
Name: id, dtype: int64

In [7]:
df01_01=df01.groupby(['site','type','time','timeline'])['id'].count().reset_index(name='n_month')
df01_02=df01.groupby(['site','time','timeline'])['id'].count().reset_index(name='n_month_all')
df01_01=pd.merge(df01_01,df01_02)
df01_01['percent_month']=df01_01.n_month/df01_01.n_month_all

#df01_02=pd.pivot_table(df01_01,index=['site','type'],values=['percent'],columns=['time'])
#df01_02.columns=df01_01.time.unique()
#df01_02=df01_02.reset_index()
df01_02=df01_01.copy()
df01_02.type=df01_02.type.apply(lambda x:str(x))
df01_02.type=df01_02.type.replace('1','type1:new')
df01_02.type=df01_02.type.replace('2','type2:active')
df01_02.type=df01_02.type.replace('3','type3:1yr~3yr')
df01_02.type=df01_02.type.replace('4','type4:3yr~')

In [8]:
df01_02

,site,type,time,timeline,n_month,n_month_all,percent_month
0,1G30林口中山店,type1:new,201907,1,212,1638,0.129426
1,1G30林口中山店,type2:active,201907,1,783,1638,0.478022
2,1G30林口中山店,type3:1yr~3yr,201907,1,221,1638,0.134921
3,1G30林口中山店,type4:3yr~,201907,1,422,1638,0.257631
4,1G30林口中山店,type1:new,201908,2,158,2875,0.054957
...,...,...,...,...,...,...,...
455,1G46台中復興店,type4:3yr~,202101,2,823,3584,0.229632
456,1G47龍潭北龍店,type1:new,202101,1,250,2117,0.118092
457,1G47龍潭北龍店,type2:active,202101,1,964,2117,0.455361
458,1G47龍潭北龍店,type3:1yr~3yr,202101,1,306,2117,0.144544
459,1G47龍潭北龍店,type4:3yr~,202101,1,597,2117,0.282003

In [9]:
df02_01=df02.groupby(['site','type','time','timeline'])['id'].count().reset_index(name='n_accum')
df02_01['n_accum']=df02_01.groupby(['site','type'])['n_accum'].cumsum()
df02_02=df02.groupby(['site','time','timeline'])['id'].count().reset_index(name='n_accum_all')
df02_02['n_accum_all']=df02_02.groupby(['site'])['n_accum_all'].cumsum()
df02_01=pd.merge(df02_01,df02_02)
df02_01['percent_accum']=df02_01.n_accum/df02_01.n_accum_all

#df02_02=pd.pivot_table(df02_01,index=['site','type'],values=['percent'],columns=['time'])
#df02_02.columns=df02_01.time.unique()
#df02_02=df02_02.reset_index()
df02_02=df02_01.copy()
df02_02.type=df02_02.type.apply(lambda x:str(x))
df02_02.type=df02_02.type.replace('1','type1:new')
df02_02.type=df02_02.type.replace('2','type2:active')
df02_02.type=df02_02.type.replace('3','type3:1yr~3yr')
df02_02.type=df02_02.type.replace('4','type4:3yr~')

In [10]:
df02_02

,site,type,time,timeline,n_accum,n_accum_all,percent_accum
0,1G30林口中山店,type1:new,201907,1,212,1638,0.129426
1,1G30林口中山店,type2:active,201907,1,783,1638,0.478022
2,1G30林口中山店,type3:1yr~3yr,201907,1,221,1638,0.134921
3,1G30林口中山店,type4:3yr~,201907,1,422,1638,0.257631
4,1G30林口中山店,type1:new,201908,2,370,4138,0.089415
...,...,...,...,...,...,...,...
455,1G46台中復興店,type4:3yr~,202101,2,1262,5325,0.236995
456,1G47龍潭北龍店,type1:new,202101,1,250,2117,0.118092
457,1G47龍潭北龍店,type2:active,202101,1,964,2117,0.455361
458,1G47龍潭北龍店,type3:1yr~3yr,202101,1,306,2117,0.144544
459,1G47龍潭北龍店,type4:3yr~,202101,1,597,2117,0.282003

In [11]:
df03=pd.merge(df01_02,df02_02)

In [12]:
df03

,site,type,time,timeline,n_month,n_month_all,percent_month,n_accum,n_accum_all,percent_accum
0,1G30林口中山店,type1:new,201907,1,212,1638,0.129426,212,1638,0.129426
1,1G30林口中山店,type2:active,201907,1,783,1638,0.478022,783,1638,0.478022
2,1G30林口中山店,type3:1yr~3yr,201907,1,221,1638,0.134921,221,1638,0.134921
3,1G30林口中山店,type4:3yr~,201907,1,422,1638,0.257631,422,1638,0.257631
4,1G30林口中山店,type1:new,201908,2,158,2875,0.054957,370,4138,0.089415
...,...,...,...,...,...,...,...,...,...,...
455,1G46台中復興店,type4:3yr~,202101,2,823,3584,0.229632,1262,5325,0.236995
456,1G47龍潭北龍店,type1:new,202101,1,250,2117,0.118092,250,2117,0.118092
457,1G47龍潭北龍店,type2:active,202101,1,964,2117,0.455361,964,2117,0.455361
458,1G47龍潭北龍店,type3:1yr~3yr,202101,1,306,2117,0.144544,306,2117,0.144544
459,1G47龍潭北龍店,type4:3yr~,202101,1,597,2117,0.282003,597,2117,0.282003

In [13]:
j

'202101'

In [14]:
df03.to_excel(r'C:\Users\RT009223\TestriteGroup\滲透率專案\06_TLW社區店\TLW社區店'+j+'會員組成.xlsx',index=0)

In [15]:
j

'202101'